- locales/ja.po
I am a Japanese native speaker, and this is updated Japanese translations of wxmaxima.
> Updated Japanese translations

- locales/ja.po
This is a Japanese translations update.
> Update Japanese translations

- locales/uk.po
The update is tested with msgfmt -vc and on the running application (in vivo).
Many thanks for merging this request.
> Update Ukrainian translation

- configure.ac
- data/wxmathml.lisp
Let me update Turkish translation.... 15.08 looks great. Congrulations
> Version 15.08

- src/GroupCell.cpp
Allows pure (La)TeX code to be written in comments and parsed as needed in TeX.
> Removed bug to allow export of TeX-ed comments

- data/wxmathml.lisp.in
This PR resolves [issue #723](https://github.com/andrejv/wxmaxima/issues/723).
> In wxbug_report, update info for Maxima bug reports.

- src/MathCtrl.h
- src/wxMaximaFrame.cpp
Thanks for fixing these minor typos.
> Fix minor typos in messages

- locales/ca.po
- locales/cs.po
- locales/da.po
- locales/de.po
- locales/el.po
- locales/en.po
- locales/es.po
- locales/fi.po
- locales/fr.po
- locales/gl.po
- locales/hu.po
- locales/it.po
- locales/ja.po
- locales/kab.po
- locales/nb.po
- locales/pl.po
- locales/pt_BR.po
- locales/ru.po
- locales/tr.po
- locales/uk.po
- locales/wxMaxima.pot
- locales/zh_CN.po
- locales/zh_TW.po
I've updated Japanese translation of wxMaxima.
Before: 776 translated messages, 77 fuzzy translations, 255 untranslated messages.
After: 903 translated messages, 205 untranslated messages.
> Update Japanese translation

- locales/it.po
> Updated Italian translation

- src/GroupCell.cpp
Clang warns about these things :) PVS Studio does too.
> Fix a typo that is an algebra bug.

- data/create_index.py
> some changes for python3 compatibility

- src/wxMaxima.cpp
Closes #1115
See also: https://wiki.wxwidgets.org/WxFileSelector
> wxFileSelector: always check for an empty return value

- data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
Enhance AppData file:
* Add `provides` tag (binary)
* Add `translation` tag (gettext)
See also:
https://github.com/flathub/flathub/wiki/AppData-Guidelines#translations
> If the app uses gettext `.mo` or Qt `.qm` files, you’ll need to provide the prefix of these files with a `<translation/>` tag
> Enhance AppData file

- data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
Fix AppData file:
* Fix indents
* `<li>` cannot end in `.`
> Fix AppData file

- src/wxMaxima.cpp
Without this patch, partial writes go unnoticed by wxMaxima, resulting in Maxima seeing a partial command followed immediately by whatever the next command to be written happens to be. On OpenBSD, this seems to happen more often than on other OSes, as I consistently see this message on startup:
```
Maxima encountered a Lisp error:
Unexpected end of file on #<string-input stream from "(:lis...">.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
Maxima encountered a Lisp error:
The function READ-WXMAXIMA-VERSION is undefined.
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
```
This is caused by wxMaxima's startup commands being incompletely written.
Regardless of which platforms this bug manifests on, this is the documented …
> Handle partial writes and errors in SendMaxima

- examples/fittingEquations.wxm
Corrected average and the confusing words "quite in"
> One spelling and confusing words.

- examples/solvingEquations.wxm
> Clarifying English

- src/Image.cpp
- src/ImgCell.cpp
This fixes #1244. All image output is affected by this bug.
> Fix printed image size

- src/Cell.cpp
- src/Cell.h
- src/GroupCell.cpp
- src/Worksheet.cpp
This gives us a chance of being somewhat accessible at least.
> Fix the accessibility method signatures so that they actually implement wxAccessible API.

- src/wxMaximaFrame.cpp
> Do not forcibly show the Greek Letters pane by default.

- src/SvgBitmap.cpp
- src/SvgBitmap.h
Do not reinterpret the SVG data - just decompress it and pass it onto the parser.
> Fix SVG rendering.

- src/GroupCell.cpp
- src/GroupCell.h
- src/Worksheet.cpp
- src/Worksheet.h
This is minor but helps - the line array the parser works on is not changed nor copied.
> Copy less in the wxm parser

- src/cells/EditorCell.cpp
- src/cells/EditorCell.h
- src/wxMaxima.cpp
> Feature/koen gu/find fixes

- src/ConfigDialogue.cpp
- src/main.cpp
- src/wxMaxima.cpp
Made some minor comment edits and one a for an replacement.
> Fix typo rag

- info/wxmaxima.md
A minor grammar fix.  Makes it easier to understand.
> A minor grammar fix

- src/wxMaxima.cpp
Maybe wxT will do it without going to unicode.
> Fix the apostrophe in isn't

- info/wxmaxima.md
Capitalize wxMaxima at the start of sentences.
> Wx maxima rag

- src/wxMathML.lisp
- src/wxMaxima.cpp
Restored the original change and changed the command ending to a semicolon.
> Fix wxbug report

- src/wxMathML.lisp
> Use maxima build_info

- src/cells/EditorCell.cpp
> EditorCell::FindMatchingQuotes(): check m_positionOfCaret bounds

- examples/fastListAccess.wxm
- examples/memoizing.wxm
Sentence correction in some Tutorials.
> Rag spelling

- NEWS.md
- src/wxMathML.lisp
Added indentation for values and enabled it to be called by the menu wxbuild_info.
> Bug fix rgobeli info format

- README.md
I notice a spelling typo for a recent change.
> Spelling and punctuation

- examples/fittingEquations.wxm
> Update punctuation in fittingEquations.wxm

- src/Configuration.cpp
- src/Configuration.h
- src/dialogs/ConfigDialogue.cpp
- src/dialogs/ConfigDialogue.h
- src/wxMaxima.cpp
Both are broken, but each in a different way.
> allow to choose between gnuplot and wgnuplot

- data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
List nesting causes package build error in Flatpak.
> appdata fix for Flatpak

- locales/manual/ru.po
> Add Russian translation

- locales/manual/fr.po
fr.po for the translation of the manual in french
it is a new file since no translation exists
> Translation of the manual in french
