src/Config.cpp
Fix a typo in src/Config.cpp. We need to update *.po files.
=> Fix a typo "putput" instead of "output"

src/ConfigDialogue.cpp, src/ConfigDialogue.h, src/IntegrateWiz.cpp, src/IntegrateWiz.h, src/LimitWiz.cpp, src/LimitWiz.h, src/MatWiz.cpp, src/MatWiz.h
This PR replaces the use of `wxComboBox` as drop-down list by `wxChoice`.
On OS X and GTK+, a `wxChoice` and a `wxComboBox` with `wxCB_DROPDOWN | wxCB_READONLY` are different.  The former is preferable because the user can click anywhere on the control to show the list, not limited to the button on the right.
=> Use wxChoice instead of wxComboBox with wxCB_DROPDOWN | wxCB_READONLY for drop-down list.

data/Makefile.am, data/wxMaxima.appdata.xml
* Change appdata filename to be consistent with .desktop file name
* The reference to the .desktop file in appdata.xml was to
wxmaxima.desktop, while the installed .desktop file was
called wxMaxima.desktop, fix this.
The renaming of the appdata file is not strictly required but recommended for distro-specific package managers to pick up the appdata file consistently [see http://dominique.leuenberger.net/blog/2016/07/how-to-fix-my-application-does-not-show-up-in-software-centers/]. Comments welcome.
Thanks!
=> Fix filename and .desktop reference for appdata.xml.

locales/ca.po, locales/cs.po, locales/da.po, locales/de.po, locales/el.po, locales/en.po, locales/es.po, locales/fi.po, locales/fr.po, locales/gl.po, locales/hu.po, locales/it.po, locales/ja.po, locales/kab.po, locales/nb.po, locales/pl.po, locales/pt_BR.po, locales/ru.po, locales/tr.po, locales/uk.po, locales/wxMaxima.pot, locales/zh_CN.po, locales/zh_TW.po, src/wxMaxima.cpp
Use formatting function to include the file name in the message, instead of string concatenation.
=> Enable better translation of "save changes" dialog

locales/it.po
Accel key names seems to be untranslatable since when I start wxMaxima it complains with a series of:
13:31:39: Debug: Unknown accel modifier: 'maiusc'
Probably we should open a bug report for making translatable the accel key names...
=> Updated Italian translation unstranslating untranslatable accel key names

src/wxMaxima.cpp, src/wxMaxima.h
Instead of escaping spaces, I rewrote the code to escape quotation marks and to enclose the path itself by quotation marks. Now everything seems to work properly on Windows and Linux.
=> Changed the Maxima path escaping stuff to work properly.

src/MathCtrl.cpp
Based on changes suggested by @kosilin
However I'm not sure if antialiassing works properly in wxgtk3 now: https://imgur.com/5J66j1D
on the left wxMaxima 18.02 on the right current master with this patch. One can see difference when looking at parenthesis.
=> fix wxgtk2 and wxgtk3

data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
There should be only one default screenshot.
Property `type="default"` is intended to indicate the application's primary screenshot.
This patch has already been applied to the flatpak package.
https://github.com/flathub/flathub/pull/801#issuecomment-457083756
=> Fix AppData file: Make only one default screenshot

data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
`ModernToolkit` in `kudos` means that the application uses a modern toolkit like Gtk+3 or Qt5. 
However, wxMaxima, just like almost every wxWidgets app, can use Gtk+2 as well.
This is why we should leave it to the automatic detection mechanism in `appstream-builder`.
See also:
https://github.com/flathub/flathub/wiki/AppData-Guidelines#kudos
https://gitlab.gnome.org/GNOME/gnome-software/blob/master/doc/kudos.md#kudos-used-in-software
---
To remove `ModernToolkit` from `kudos` I used the following command:
```
xmlstarlet ed --inplace -d '/component/kudos/kudo[text()="ModernToolkit"]' data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
```
That's why it has fixed a few things related to XML as well.
=> Fix AppData file: Remove ModernToolkit from kudos

src/Worksheet.cpp
`Worksheet.cpp`: Call `wxAutoBufferedPaintDC::SetPen(const wxPen&)` correctly
Closes #1121
=> Call wxAutoBufferedPaintDC::SetPen() correctly

src/Worksheet.cpp
Unfortunately, the last update (_19.05.0_) has broken the program under wxWidgets 3.1.
It doesn't now correctly display the area when scrolling.
Example input:
```
for i thru 100 do display(i!);
```
Result:
"wxMaxima_19.05.0_wxWidgets-3.1.png")
The error does **not** occur in wxWidgets 3.0 (versions 3.0.2 and 3.0.4 were tested, the second one with both toolkits: gtk+2 and gtk+3).
I can also confirm that this error did **not** occur in the previous version (_19.04.3_).
---
This patch fixes the bug on GNOME 3.32 runtime in Flatpak when using wxGTK3 3.1.2.
It applies only to wxGTK3 in wxWidgets 3.1, so it shouldn't break anything else.
Please keep in mind that all major Linux distribution use wxWidgets 3.0 by default. This includes EL, Fedora, SLE, openSUSE, Ubuntu LTS and Debian stable. …
=> Another attempt to fix #1113

data/io.github.wxmaxima_developers.wxMaxima.appdata.xml
AppData validation has become more strict:
* longest allowed caption is 50 chars
* `<li>` cannot contain a hyperlink
=> Fix AppData file

src/wxMaxima.cpp
`2^32` equals `34`, which does not do what this code wants.
=> Fix incorrect use of ^ operator

src/wxMaxima.cpp
Found by a compiler warning:
```
/usr/pkg/pobj/wxMaxima-19.08.1/wxmaxima-Version-19.08.1/src/wxMaxima.cpp:8742:10: warning: comparison of two values with different enumeration types in switch statement ('TextStyle' and 'GroupType') [-Wenum-compare-switch]
case GC_TYPE_HEADING6:
^~~~~~~~~~~~~~~~
```
The intent of this code appears to be to restrict changing the cell's style to text cells only, but the wrong method call was used to get the cell's type.
This created a bug whereby changing the cell style appeared to work correctly for text cells, but non-text cells were broken. To reproduce:
1. Go to Cell -> Insert image...
1. Insert an image cell (with any image)
1. Click on the text at the top of the image cell to activate it.
1. Use the drop-down menu to change its type from Maths to any …
=> Match the group type correctly in ChangeCellStyle

src/CMakeLists.txt
Currently, translation files (`*.mo`) are missing from the application bundle.  Thus, translations are not applied on macOS.
This PR adds build rules to copy them; i.e.
* `<build dir>/locale/<LANG>/LC_MESSAGES/wxMaxima.mo` -> `wxMaxima.app/Contents/Resources/locale/<LANG>/LC_MESSAGES/wxMaxima.mo`
* `<source dir>/locales/wxwin/<LANG>.mo` -> `wxMaxima.app/Contents/Resources/locale/<LANG>/LC_MESSAGES/wxMaxima-wxstd.mo`
=> Copy translation files into the application bundle

src/CMakeLists.txt
Until now, the app was run with Apple's placeholder app icon
because the wxmac.icns was not mentioned in the Info.plist
file, despite being in the bundle.
=> Use the existing Mac icon by setting the icon filename.

src/Configuration.cpp
'Text cell' description restored for the TS_TEXT style. 
'Heading 1-4' in parentheses added to descriptions to make styles hierarchy more comprehensible.
=> cell styles names corrections and extensions

src/Dirstructure.cpp, src/Dirstructure.h, src/wxMaxima.cpp
This PR enhances the mechanism to find gnuplot:
- Centralised two different places in the code searching for gnuplot into Directorystructure.cpp
- Added a Macports specific search path for OSX
- Added a mechanism to easily patch the MacPorts root folder to the actual prefix chosen on each system
- Always set m_gnuplotcommand to a path of gnuplot in case gnuplot can be found and do this only once, in the constructor of wxMaxima and when settings are read in.
=> Enhance mechanism to find gnuplot

examples/fittingEquations.wxm
There should be an a before consonant sound.
=> Fixed the an to a.

src/EditorCell.cpp
This fixes an out-of-bounds access crash when adding a character to a freshly created editor cell.
To reproduce:
1. Build wxWidgets 3.1.3 build using MSVC 2019 16.5.4, 64 bits debug build.
2. Build wxMaxima in the same way.
3. Start wxMaxima, press any printable key (e.g. simply a). A new EditorCell is created, parenthesis matching is attempted, and promptly crashes since the cell is empty and an a call is made to wxString::GetChar(-1).
=> Fix out-of-bounds string access in EditorCell::FindMatchingParens().

src/ConfigDialogue.cpp, src/Configuration.cpp, src/EditorCell.cpp, src/FontCache.cpp, src/FontCache.h, src/IntCell.cpp, src/ParenCell.cpp, src/SqrtCell.cpp, src/SumCell.cpp, src/TextCell.cpp, src/TextStyle.cpp
wxMaxima wastes lots of time copying, destroying and reinstantiating objects. For a long document (~80 printed pages), this causes tens of millions of unnecessary allocations, copies and destructions across a wide range of objects (this problem is pervasive). 
This is a small step towards resolving #1185 - not nearly done yet of course.
On a test document, just the wxFont was reinstantiated hundreds of thousands of times. All that works was done just to utilize about 50 unique fonts. wxFont creation is extremely slow: it had to create and destruct native font handles. Fixing that alone cuts down document load times between 15-50% for me.
Sample debug session;
```
06:03:42: Debugging starts
~FontCache: hits=215904 misses=59 h:m ratio=3659.39
06:04:26: Debugging has finished
```
There's …
=> Cache wxFont instances, reducing the number of wxFont instance churn by a factor of 5000+

src/Autocomplete.cpp, src/Configuration.cpp, src/Configuration.h, src/EditorCell.cpp, src/EditorCell.h, src/GroupCell.cpp, src/SvgBitmap.cpp
- Gets rid of two instances of manual C-string memory management.
- Fixes UB where a `strdup` allocation was freed using `delete`.
- Moves the escape codes to a static `unordered_map`, so that instantiating `Configuration` doesn't unnecessarily redo that every time.
=> Refactors memory and escapes

src/EditorCell.h
This pointer was not initialized and could be potentially used uninitialized.
=> Fix an uninitialized member.

src/WXMformat.cpp
Change the input arg for `getLinesUntil` to accept `wxString` instead of `wxChar *`. Fixes #1324.
=> Fix type conversion from wxChar * to wxString

src/wxMaxima.cpp
In latest wxMaxima the titles of the windows for selecting list elements (extract all but 1st/last n elements) are exchanged. This commit shoud fix it.
=> Fix strings for list rest options (in menu)

src/ButtonWrapSizer.cpp
When wxWidgets is built with STL containers, `wxSizerItemList::compatibility_iterator` must be used instead of `wxSizerItemList::Node *`. Just use `auto` to avoid explicitly determining which kind of iterator to use.
Fixes #1463
=> Fix iterator use when wxWidgets is built with STL.

.gitignore, src/Image.cpp
This PR fixes a bug that OMP locks are released twice, once via a helper class and once explicitly. This leads to crashes on Mac if OMP is enabled.
This fixes #1474
=>  Fix double release of OMP locks in several places

src/ConfigDialogue.cpp, src/ConfigDialogue.h
This fixes the issue that on macOS the preferences panel size was set to very small after changing the panel.
This also slightly adjusts the panel size, so that all panels fit on Mac (I made it a bit wider and a bit less tall, from 600x800 to 640x720). It needs to be checked if this also works nicely on other systems, but anyway scroll bars are enabled in case the panels are too large on some systems.
@gunterkoenigsmann : FYI.
=> Fix and adjust preferences dialog  size

src/cells/Cell.cpp, src/cells/SubSupCell.cpp, src/cells/SubSupCell.h, src/cells/TextCell.cpp, src/cells/TextCell.h
This PR closes #1575.
First commit fixes the `ToString` (copy) for the inputs below, by adding a default `GetDiffPart` function that should work with many cell types:
```
diff(f(x[1]), x[1], 1);
```
```
'diff(f(x), g(x));
```
```
'diff(f(x),g(x),2);
```
Second commit fixes it for this input, where the variable of differentiation has a subscript and the order of differentiation is higher than one (therefore `SubSupCell` is used):
```
'diff(f(x[1]),x[1],3);
```
---
One problem that remains is that `'diff(f(x), x^2, 1)` results in the operator `d/(dx^2)`, and wxMaxima takes the exponent 2 in the denominator as the order of differentiation. But I think this should be a separate issue.
=> Make GetDiffPart work with different cell types

src/ConfigDialogue.cpp, src/ConfigDialogue.h, src/Configuration.cpp, src/Configuration.h, src/MathParser.cpp, src/Worksheet.cpp, src/Worksheet.h, src/cells/GroupCell.cpp, src/cells/ImgCell.cpp, src/cells/ImgCell.h, src/wxMaxima.cpp
This branch adds "Reload" and "Change Image" items to the image cell context menu:
- "Reload" reloads the file from disk using the original image filename and path. This is useful if the image was edited externally and it needs to be updated in the worksheet.
- "Change Image" opens a file dialog where an alternative file for replacing the current image can be selected.
The original image filenames and paths are stored in the worksheet file to keep the reload capability after re-opening the worksheet. Since users may not want to leak filenames and paths in their worksheets, a configuration checkbox for disabling storing the filenames has also been implemented.
The option defaults to off (not storing in the worksheet file) which prevents `ImgCell::ToXML` from outputting the filenames.
If a …
=> Enable reloading and changing images inserted via "Cell" -> "Insert Image..."

data/wxMathML.lisp
In wxhistogram, call histogram_description to obtain graphic object to plot, instead of calling histogram.
Likewise for wxscatterplot, wxbarsplot, wxpiechart, and wxboxplot: call scatterplot_description, barsplot_description, piechart_description, and boxplot_description, respectively.
Fixes bug #1601: wxhistogram provokes "2D graphic object not recognized"
=> Fix bug #1601: wxhistogram provokes "2D graphic object not recognized"

src/wxMaxima.cpp
Just setting m_fileSaved to false does not work, because it gets overwritten at
other locations.
=> Correctly set the document saved state when the size of an image is changed.

src/Worksheet.cpp, src/cells/EditorCell.cpp
Fixes the bug #1624.
The type of clipboard texts from other Apps is usually `kUTTypeUTF8PlainText = "public.utf8-plain-text"` corresponding to `wxDF_UNICODETEXT`, while current implementation only accepts type of `kUTTypeTraditionalMacText = "com.apple.traditional-mac-plain-text"` corresponding to `wxDF_TEXT`. Therefore accepting `wxDF_UNICODETEXT` solves this problem.
=> Fix bug #1624: Can paste text from other apps in macOS

.github/workflows/codeql-analysis.yml, .github/workflows/compile_mac.yml, .github/workflows/compile_ubuntu.yml, .github/workflows/compile_windows.yml, .github/workflows/cppcheck.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src/wizards/Gen1Wiz.cpp, src/wizards/Gen1Wiz.h, src/wizards/Plot2dWiz.cpp, src/wxMaxima.cpp, src/wxMaximaFrame.cpp
On macOS, wxMaxima uses a single process to show all document windows.  A consequence is, use of `ShowModal` make background windows unusable.
This PR improves the situation by making various dialogs use `ShowWindowModalThenDo`, which allows other windows to interact with user.
=> Make various dialogs window-modal

src/wxMathML.lisp
the wxbuild_info was overwritten by the last line. I am not sure how to correct it. This is a temp fix.
=> fix the wxbuild_info in wxbug_report

src/wxMaxima.cpp
By putting a $ at the end of the command, we suppress the false output of the command end.
The wxbug_report now works without the false output at the end.
=> Suppress the false at the end

CMakeLists.txt, src/Version.h.cin
MS Windows is limited to ridiculously short command lines.
=> A try to make the command line for the build commands shorter

src/wizards/SystemWiz.cpp
Otherwise, an assertion fails, when trying to solve a linear system (Equations > Solve symbolically > Solve Linear System...):
> /usr/include/wx-3.2/wx/strvararg.h(484): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type
=> SystemWiz: fix invalid format specifier

src/Configuration.cpp
Somehow I ended up with `autoSaveMinutes=0` in my wxMaxima.conf. And because `m_autoSaveTimer` had an interval of 0, wxMaxima would barely run because it was spending all its time in that timer's handler.
On Linux.
```
$ wx-config --selected-config
gtk3-unicode-3.2
```
=> Don't allow zero for autoSaveMinutes.

src/main.cpp, src/wxMaxima.h
Removed a compiler warning by switching to automatic pointers that issue a free() when appropriate.
=> remove a compiler warning

src/cells/EditorCell.cpp
When selecting from right to left, the variables are reversed.
=> For a one-way selection
